name: Pull Request Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate Code
        run: echo "Linting HTML and CSS will be handled manually for now"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Website
        run: echo "Building the static website will be handled manually"
